name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  push: {branches: master}
  pull_request:
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: omelkonian/setup-agda@master
        with:
          agda-version: 2.6.4
          stdlib-version: 1.7.3
          main: Main
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          measure-typechecking: true
